### Exercise B

Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.


In [15]:
import numpy as np #it imports the Numpy Libary, in short nickname is np

In [16]:
B = np.ones((5, 5), dtype=int)  #creates 5 rows and 5 columns filled, specifying the data type as 'int'

In [17]:
print("Shape:", B.shape) #it tells the form  of the array, it returns 5 rows and 5 columns

Shape: (5, 5)


In [18]:
print("Size:", B.size) #it calculates the total count of all elements stored in the object

Size: 25


In [19]:
print("Dimensions:", B.ndim) #this stands for number of dimensions

Dimensions: 2


In [20]:
print("\nArray B:\n", B) #will display the created array


Array B:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
